name: CMake Build

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'openanolis/anolisos:8.8'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -fsSLO --compressed https://cmake.org/files/v3.22/cmake-3.22.3-linux-x86_64.tar.gz
          tar -zxvf cmake-3.22.3-linux-x86_64.tar.gz -C /usr  --strip-components=1 --no-same-owner
          yum install -y which git wget rpm rpm-build cpio gcc gcc-c++ make glibc-devel glibc-headers libstdc++-static binutils openssl-devel libaio-devel zlib zlib-devel bison flex java-11-openjdk
      - name: Configure and generate
        run: mkdir build && cd build && cmake ..
      - name: Compile and link
        run: cd build && cmake --build . -j 8
